Corrected sources path for clean-up step. Added handling for builds with no patches.

diff --git a/.github/workflows/build-qc-bsp-reusable.yml b/.github/workflows/build-qc-bsp-reusable.yml
--- a/.github/workflows/build-qc-bsp-reusable.yml
+++ b/.github/workflows/build-qc-bsp-reusable.yml
@@ -78,7 +78,7 @@ env:
   #Build constants
   CONTAINER_NAME: "ci_qualcomm_${{ github.run_id }}"
   CI_DIR: "/mnt/nvme1/qcom_ci"
-  SRC_REPO: "qcs8550-le-1-0_amss_standard_oem_apqgps"
+  QCS_SOURCES: "qcs8550-le-1-0_amss_standard_oem_apqgps"
   PYENV: "3.8.16"
 
   #Workflow development variables  
@@ -168,43 +168,46 @@ jobs:
 
           cd "${BUILD_PROJECT_PATH}"
 
-          #extract patches if present if flagged
+          #extract patches if applicable
           if [ $HAS_PATCHES == 1 ]; then
               tar -xf "SOURCES/patches/patches.tar.gz" -C .
           fi
           
-          #extract source files
-          tar -xf "${CI_DIR}/builds/SHARED_SOURCES/${SRC_REPO}.tar.gz" -C .
+          #extract Qualcomm source files
+          tar -xf "${CI_DIR}/builds/SHARED_SOURCES/${QCS_SOURCES}.tar.gz" -C .
           
       # - name: Build container and initialize user permissions & ownership
       #   timeout-minutes: 10
       #   run: |
       #     set +x
+      #     #get host user and group IDs to pass to container
       #     export HOST_UID=$(id -u)
       #     export HOST_GID=$(id -g)
-
+          
+      #     #build container
       #     docker build -f "${CI_DIR}/docker/qc_ci_docker" \
       #     -t imdt-qualcomm-ci:"${DOCKER_VER}" \
       #     for_docker
 
+      #     #run container
+      #     #pass ID's to entry-point script to setup user permissions and ownership
       #     docker run --rm -d \
       #     --name "$CONTAINER_NAME" \
-      #     -e SRC_REPO="$SRC_REPO" \
       #     -e MANI_REPO="$MANI_REPO" \
       #     -e MANI_BRANCH="$MANI_BRANCH" \
       #     -e MANI_XML="$MANI_XML" \
       #     -e BUILD_RELEASE_NAME="$BUILD_RELEASE_NAME" \
-      #     -e QCOM_ROOT_DIR="/home/dev/Qualcomm/${SRC_REPO}" \
+      #     -e QCOM_ROOT_DIR="/home/dev/Qualcomm/${QCS_SOURCES}" \
       #     -e MACHINE="$BUILD_MACHINE" -e DISTRO="$BUILD_DISTRO" -e PYENV="$PYENV" \
       #     -v "${PWD}/for_docker:/workflows" \
-      #     -v "${BUILD_PROJECT_PATH}/home/dev/Qualcomm" \
+      #     -v "${BUILD_PROJECT_PATH}:/home/dev/Qualcomm" \
       #     -v "${CI_DIR}/scripts/:/home/dev/tools/" \
       #     imdt-qualcomm-ci:${DOCKER_VER} $HOST_UID $HOST_GID \
       #     sleep infinity
 
       #     #stream entry point script logs
       #     docker logs -f "${CONTAINER_NAME}" &
-      #     LOG_PID     
+      #     LOG_PID=$!
 
       #     #wait for entry script to signal completion
       #     until docker exec "${CONTAINER_NAME}" test -f /tmp/ready; do sleep 2; done
@@ -213,7 +216,12 @@ jobs:
       #     kill $LOG_PID || true
 
       #     #verify that IDs are correct and ownership has been transferred correctly
-      #     $DOCKER_EXEC "${CONTAINER_NAME}" bash -lc 'ls -la; id'
+      #     result=$($DOCKER_EXEC "${CONTAINER_NAME}" bash -lc 'id')
+
+      #     if [[ "$result" =~ "uid=$HOST_UID($HOST_UID) gid=$HOST_GID($HOST_GID)" ]]; then
+      #       echo "ERROR: User IDs do not match"
+      #       exit 1
+      #     fi
 
       # - name: Build netrc
       #   run: |
@@ -323,11 +331,13 @@ jobs:
         if:  ${{ always() && env.CLEAN_UP == '1' }}
         run: |
           set -euo pipefail -x
-          [ -d "${BUILD_PROJECT_PATH:?}/${BUILD_VER:?}/qcs8550-le-1-0_amss_standard_oem_apqgps" ] && \
-          rm -rf "${BUILD_PROJECT_PATH:?}/${BUILD_VER:?}/qcs8550-le-1-0_amss_standard_oem_apqgps"
-          [ -d "${BUILD_PROJECT_PATH:?}/${BUILD_VER:?}/patches" ] && \
-            rm -rf "${BUILD_PROJECT_PATH:?}/${BUILD_VER:?}/patches"
+          [ -d "${BUILD_PROJECT_PATH:?}/qcs8550-le-1-0_amss_standard_oem_apqgps" ] && \
+          rm -rf "${BUILD_PROJECT_PATH:?}/qcs8550-le-1-0_amss_standard_oem_apqgps"
           
+          if [ $HAS_PATCHES == 1 ]; then
+            [ -d "${BUILD_PROJECT_PATH:?}/SOURCES/patches" ] && \
+              rm -rf "${BUILD_PROJECT_PATH:?}/SOURCES/patches"
+          fi            
       - name: Clean up container and image
         if: ${{ always() }}
         run: |
