Corrected env variable assignment. Simplified SDK step logic.

diff --git a/.github/workflows/build-qc-bsp-reusable.yml b/.github/workflows/build-qc-bsp-reusable.yml
--- a/.github/workflows/build-qc-bsp-reusable.yml
+++ b/.github/workflows/build-qc-bsp-reusable.yml
@@ -121,11 +121,11 @@ jobs:
       DISTRO: ${{ inputs.BUILD_DISTRO }}
       IMAGE: ${{ inputs.BUILD_IMAGE }}
       #This evaluates to [project_path]/[version]
-      BUILD_PROJECT_PATH: ${{ format('{0}/{1}', inputs.build_project_path, inputs.build_version) }}
-      BUILD_DOCKER: ${{ inputs.build_docker }}
-      HAS_PATCHES: ${{ inputs.build_patches }}
-      PATCH_SCRIPT_PATH: ${{ inputs.build_patch_script_path }}
-      RELEASE_NAME: ${{ inputs.build_release_name }}
+      BUILD_PROJECT_PATH: ${{ format('{0}/{1}', inputs.BUILD_PROJECT_PATH, inputs.BUILD_VERSION) }}
+      BUILD_DOCKER: ${{ inputs.BUILD_DOCKER }}
+      HAS_PATCHES: ${{ inputs.BUILD_HAS_PATCHES }}
+      PATCH_SCRIPT_PATH: ${{ inputs.BUILD_PATCH_SCRIPT_PATH }}
+      RELEASE_NAME: ${{ inputs.BUILD_RELEASE_NAME }}
       PYENV: ${{ inputs.PYENV }}
       QCS_SOURCES: ${{ inputs.QCS_SOURCES }}
       SKIP_STEPS: ${{ inputs.SKIP_STEPS }}
@@ -313,16 +313,20 @@ jobs:
           
           #locate generated SDK script and rename
           SDK_DIR="${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/apps_proc/build-${DISTRO}/tmp-glibc/deploy/sdk/"
+          #output name format: [release_name_without_prebuilt_suffix]-sdk-v[build_version].sh
+          OUTPUT_NAME="${SDK_DIR}/${RELEASE_NAME%_prebuilt*}-sdk-v${BUILD_VERSION}.sh"
           
-          #verify that there is exactly one script matching          
-          mapfile -t matches < <(find "$SDK_DIR" -maxdepth 1 -type f -name "*${DISTRO}*.sh")
-          if (( ${#matches[@]} == 1 )); then
-            #rename it to [project_name]-sdk-v[version].sh (e.g., imsu_glasses_sdk-v1.0.0.sh)
-            mv -- "${matches[0]}" "${SDK_DIR}/${RELEASE_NAME%_prebuilt*}-sdk-v${BUILD_VERSION}.sh"
-          else
-            echo "Warning: Expected exactly 1 SDK file, found ${#matches[@]}. Skipping rename."
-            exit 0
+          #verify that there is exactly one sh script in SDK_DIR
+          cd "$SDK_DIR"
+          sdk_sh="$(find -maxdepth 1 -type f -name '*.sh')"
+
+          if [[ -z "$sdk_sh" ]]; then
+            echo "ERROR: No SDK files found in ${SDK_DIR}"
+            exit 1
           fi
+
+          #rename SDK script to output_name
+          mv -- "$sdk_sh" "$OUTPUT_NAME"
           '
       
       - name: Build non-HLOS components
@@ -339,10 +343,9 @@ jobs:
           $DOCKER_EXEC "${CONTAINER_NAME}" bash -c '
           set -xe
           FULL_RELEASE_NAME="${RELEASE_NAME}_v${BUILD_VERSION}"
-          OUTPUT_TAR="${FULL_RELEASE_NAME}.tar.gz"
           RELEASE_DIR="/home/dev/Qualcomm/${FULL_RELEASE_NAME}"
 
-          #if release artifact already exists, remove it
+          #if release directory already exists, remove it
           [ -d "$RELEASE_DIR" ] && rm -rf "$RELEASE_DIR"
           
           #create new release artifact
@@ -350,17 +353,18 @@ jobs:
           python3 create_release.py \
            -r "$RELEASE_DIR" \
            -x "${QCOM_ROOT_DIR}/contents.xml" \
-           -b "${QCOM_ROOT_DIR}" 
+           -b "${QCOM_ROOT_DIR}"
+          
+          #create prebuilt tarball 
+          tar -C "/home/dev/Qualcomm/" -czf "${FULL_RELEASE_NAME}.tar.gz" "${FULL_RELEASE_NAME}"
 
-          #create prebuilt tarball
-          cd /home/dev/Qualcomm
-          tar -C "$RELEASE_DIR" -czf "${OUTPUT_TAR}" .
-
-          #verify tarball creation and non-compressed directory
-          if [ -f "${OUTPUT_TAR}" ]; then
-            echo "Release artifact created at /home/dev/Qualcomm/${OUTPUT_TAR}"
+          #verify tarball creation and non-compresssed directory
+          if [ -f "/home/dev/Qualcomm/${FULL_RELEASE_NAME}.tar.gz" ]; then
+            echo "Release artifact created at /home/dev/Qualcomm/${FULL_RELEASE_NAME}.tar.gz"
             echo "Cleaning up temporary release directory..."
-            rm -rf "$RELEASE_DIR"
+            if [ -d "$RELEASE_DIR" ]; then
+              rm -rf "$RELEASE_DIR"
+            fi
           else
             echo "ERROR: Release artifact creation failed."
             exit 1
